#! /bin/zsh

# --- Coloring -----------------------------------------------------------------

alias ls='ls --color=always'
alias grep='grep --color=always'
alias tree='tree -C'
alias less='less -R'

# --- LS shortcuts -------------------------------------------------------------

alias l='ls -l'
alias la='ls -a'
alias ll='ls -la'

# --- COPY TO X CLIPBOARD ------------------------------------------------------

alias xcp='xclip -selection clipboard'
